Add eus_vive package
jsk-ros-pkg/jsk_control pull request #731
Opened 2019-09-03 09:51 UTC by knorth55

I use this ROS package to run Miraikan  openlab demo in 2019.
How to run the demo is written here https://github.com/knorth55/jsk_control/blob/4732ce5b3f76259c2c809714e16c539c47134c06/eus_vive/README.md

2021-05-12 09:29 UTC, k-okada requested changes

2021-05-12 11:28 UTC, knorth55 commented on eus_vive/kinetic.rosinstall
> +- git:
I updated to add information

2021-05-12 11:28 UTC, knorth55 commented on eus_vive/package.xml
> +  <version>0.0.0</version>
I update this package version.

2021-05-12 11:30 UTC, knorth55 commented
Now i update this PR and support spacenav_node.
`spacenav_node` publish `Joy` topic, so I can support other joy devices, too.
`omega_devices`  are a bit different because it has feedback, so i need update this package more.

2021-05-14 00:23 UTC, k-okada commented
> so i need update this package more.

OK, added `[WIP]` in the title.

2023-02-01 09:29 UTC, closed without merging